(rule
	(alias frama-c-configure)
	(deps (universe))
	(action (progn
			(echo "acsl_lsp:" %{lib-available:frama-acsl_lsp.core} "\n")
			(echo " - Frama-C:" %{lib-available:frama-c.kernel} "\n")
		)
	)
)

(library
	(name acsl_lsp)
	(public_name frama-c-acsl_lsp.core)
	(flags -open Frama_c_kernel :standard)
	(libraries 
		frama-c.kernel
		frama-c-server.core
	)
)

(plugin
	(name acsl_lsp)
	(libraries frama-c-acsl_lsp.core)
	(site (frama-c plugins))
)

