import * as assert from 'assert';
import * as vscode from 'vscode';
import * as path from 'path';
import * as fs from 'fs';
import { openBenchmark, activateExtension, cleanFile, getWorkspacePath } from './helpers';

suite('displayCILProject', () => {

    test('genere le CIL du projet multi-fichiers', async function() {
        this.timeout(120000);

        await openBenchmark('global_metrics/main.c');
        await activateExtension();

        const outFile = path.join(getWorkspacePath(), '.frama-c', 'fc_project.c');
        cleanFile(outFile);

        await vscode.commands.executeCommand('displayCILProject');

        // poll manuel
        const start = Date.now();
        let cil = '';
        while (Date.now() - start < 90000) {
            if (fs.existsSync(outFile)) {
                const content = fs.readFileSync(outFile, 'utf-8');
                if (content.length > 0 && !content.startsWith('Task in progress')) {
                    cil = content;
                    break;
                }
            }
            await new Promise(r => setTimeout(r, 1000));
        }

        console.log(`fc_project.c taille : ${cil.length} chars`);
        console.log(cil.substring(0, 300));

        assert.ok(cil.length > 0, 'fc_project.c vide ou absent');
        assert.ok(cil.includes('/* Generated by Frama-C */'), 'entete Frama-C absente');
        assert.ok(cil.includes('add'), 'fonction add absente du CIL projet');
        assert.ok(cil.includes('compute'), 'fonction compute absente du CIL projet');
    });
});