(rule (target "errno.err.oracle") (mode fallback) (action (write-file "errno.err.oracle" "")))
(rule (target "errno.res.oracle") (mode fallback) (action (write-file "errno.res.oracle" "")))
(rule (target "stdlib.err.oracle") (mode fallback) (action (write-file "stdlib.err.oracle" "")))
(rule (target "stdlib.res.oracle") (mode fallback) (action (write-file "stdlib.res.oracle" "")))
(rule (target "locale.err.oracle") (mode fallback) (action (write-file "locale.err.oracle" "")))
(rule (target "locale.res.oracle") (mode fallback) (action (write-file "locale.res.oracle" "")))
(rule (target "stdatomic.err.oracle") (mode fallback) (action (write-file "stdatomic.err.oracle" "")))
(rule (target "stdatomic.res.oracle") (mode fallback) (action (write-file "stdatomic.res.oracle" "")))
(rule (target "__fc_runtime.err.oracle") (mode fallback) (action (write-file "__fc_runtime.err.oracle" "")))
(rule (target "__fc_runtime.res.oracle") (mode fallback) (action (write-file "__fc_runtime.res.oracle" "")))
(rule (target "signal.err.oracle") (mode fallback) (action (write-file "signal.err.oracle" "")))
(rule (target "signal.res.oracle") (mode fallback) (action (write-file "signal.res.oracle" "")))
(rule (target "netdb.err.oracle") (mode fallback) (action (write-file "netdb.err.oracle" "")))
(rule (target "netdb.res.oracle") (mode fallback) (action (write-file "netdb.res.oracle" "")))
(rule (target "wchar.err.oracle") (mode fallback) (action (write-file "wchar.err.oracle" "")))
(rule (target "wchar.res.oracle") (mode fallback) (action (write-file "wchar.res.oracle" "")))
(rule (target "inttypes.err.oracle") (mode fallback) (action (write-file "inttypes.err.oracle" "")))
(rule (target "inttypes.res.oracle") (mode fallback) (action (write-file "inttypes.res.oracle" "")))
(rule (target "ctype.err.oracle") (mode fallback) (action (write-file "ctype.err.oracle" "")))
(rule (target "ctype.res.oracle") (mode fallback) (action (write-file "ctype.res.oracle" "")))
(rule (target "unistd.err.oracle") (mode fallback) (action (write-file "unistd.err.oracle" "")))
(rule (target "unistd.res.oracle") (mode fallback) (action (write-file "unistd.res.oracle" "")))
(rule (target "stdio.err.oracle") (mode fallback) (action (write-file "stdio.err.oracle" "")))
(rule (target "stdio.res.oracle") (mode fallback) (action (write-file "stdio.res.oracle" "")))
(rule (target "time.err.oracle") (mode fallback) (action (write-file "time.err.oracle" "")))
(rule (target "time.res.oracle") (mode fallback) (action (write-file "time.res.oracle" "")))
(rule (target "__fc_builtin.err.oracle") (mode fallback) (action (write-file "__fc_builtin.err.oracle" "")))
(rule (target "__fc_builtin.res.oracle") (mode fallback) (action (write-file "__fc_builtin.res.oracle" "")))
(rule (target "fenv.err.oracle") (mode fallback) (action (write-file "fenv.err.oracle" "")))
(rule (target "fenv.res.oracle") (mode fallback) (action (write-file "fenv.res.oracle" "")))
(rule (target "string.err.oracle") (mode fallback) (action (write-file "string.err.oracle" "")))
(rule (target "string.res.oracle") (mode fallback) (action (write-file "string.res.oracle" "")))
(rule (target "assert.err.oracle") (mode fallback) (action (write-file "assert.err.oracle" "")))
(rule (target "assert.res.oracle") (mode fallback) (action (write-file "assert.res.oracle" "")))
(rule (target "argz.err.oracle") (mode fallback) (action (write-file "argz.err.oracle" "")))
(rule (target "argz.res.oracle") (mode fallback) (action (write-file "argz.res.oracle" "")))
(rule (target "pwd.err.oracle") (mode fallback) (action (write-file "pwd.err.oracle" "")))
(rule (target "pwd.res.oracle") (mode fallback) (action (write-file "pwd.res.oracle" "")))
(rule (target "math.err.oracle") (mode fallback) (action (write-file "math.err.oracle" "")))
(rule (target "math.res.oracle") (mode fallback) (action (write-file "math.res.oracle" "")))
(rule (target "glob.err.oracle") (mode fallback) (action (write-file "glob.err.oracle" "")))
(rule (target "glob.res.oracle") (mode fallback) (action (write-file "glob.res.oracle" "")))

