(copy_files ../*.*)
(alias (name ptests)
  (deps (alias ptests_config)))
; TEST FILE "errno.c"
(alias (name "errno.wtests")
  (deps (alias "errno.0.exec.wtests"))) ; to performs all sub-tests related to a file
(alias (name "errno.c")
  (deps (alias "errno.0.exec"))) ; to reproduce and visualize the all sub-test outputs related to a file
(rule ; TEST #0 OF TEST FILE tests/framac_libc/errno.c
  (alias "errno.0.exec.wtests")
  (targets "errno.err.log" "errno.res.log"  )
  (deps "errno.0.exec.wtests" "../oracle/errno.res.oracle" "../oracle/errno.err.oracle"  "errno.c"  (package frama-c)  )
  (enabled_if (and true))
(action (run frama-c-wtests -brief "errno.0.exec.wtests" "frama-c -check -no-autoload-plugins -add-symbolic-path=\"/home/user/git/L1/T0304764/acsl_lsp/Acsl_lsp/_build/default:.\"     errno.c > \"errno.res.log\" 2> \"errno.err.log\"" ))
)
(rule ; REPRODUCE TEST #0 OF TEST FILE "errno.c"
  (alias "errno.0.exec")
  (deps  "errno.c"  (package frama-c)   (universe))
  (enabled_if (and true))
(action (with-accepted-exit-codes 0 (system "frama-c -check -no-autoload-plugins -add-symbolic-path=\"/home/user/git/L1/T0304764/acsl_lsp/Acsl_lsp/_build/default:.\"     errno.c")))
)
(rule ; SHOW TEST COMMAND #0 OF TEST FILE "errno.c"
  (alias "errno.0.exec.show")
  (deps  "errno.c"  (package frama-c)   (universe))
  (enabled_if (and true))
(action (system "echo 'frama-c -check -no-autoload-plugins -add-symbolic-path=\"/home/user/git/L1/T0304764/acsl_lsp/Acsl_lsp/_build/default:.\"     errno.c > \"errno.res.log\" 2> \"errno.err.log\"'"))
)
(rule
  (alias "errno.0.exec.diff")
  (enabled_if (and true))
(action (diff "../oracle/errno.res.oracle" "errno.res.log"))
)
(rule
  (alias "errno.0.exec.diff")
  (enabled_if (and true))
(action (diff "../oracle/errno.err.oracle" "errno.err.log"))
)
(alias (name "errno.diff")
  (deps (alias "errno.0.exec.diff"))
  (enabled_if (and true))
)
(alias (name "ptests_config")
  (deps (alias "errno.diff"))
  (enabled_if (and true))
)
; TEST FILE "stdlib.c"
(alias (name "stdlib.wtests")
  (deps (alias "stdlib.0.exec.wtests"))) ; to performs all sub-tests related to a file
(alias (name "stdlib.c")
  (deps (alias "stdlib.0.exec"))) ; to reproduce and visualize the all sub-test outputs related to a file
(rule ; TEST #0 OF TEST FILE tests/framac_libc/stdlib.c
  (alias "stdlib.0.exec.wtests")
  (targets "stdlib.err.log" "stdlib.res.log"  )
  (deps "stdlib.0.exec.wtests" "../oracle/stdlib.res.oracle" "../oracle/stdlib.err.oracle"  "stdlib.c"  (package frama-c)  )
  (enabled_if (and true))
(action (run frama-c-wtests -brief "stdlib.0.exec.wtests" "frama-c -check -no-autoload-plugins -add-symbolic-path=\"/home/user/git/L1/T0304764/acsl_lsp/Acsl_lsp/_build/default:.\"     stdlib.c > \"stdlib.res.log\" 2> \"stdlib.err.log\"" ))
)
(rule ; REPRODUCE TEST #0 OF TEST FILE "stdlib.c"
  (alias "stdlib.0.exec")
  (deps  "stdlib.c"  (package frama-c)   (universe))
  (enabled_if (and true))
(action (with-accepted-exit-codes 0 (system "frama-c -check -no-autoload-plugins -add-symbolic-path=\"/home/user/git/L1/T0304764/acsl_lsp/Acsl_lsp/_build/default:.\"     stdlib.c")))
)
(rule ; SHOW TEST COMMAND #0 OF TEST FILE "stdlib.c"
  (alias "stdlib.0.exec.show")
  (deps  "stdlib.c"  (package frama-c)   (universe))
  (enabled_if (and true))
(action (system "echo 'frama-c -check -no-autoload-plugins -add-symbolic-path=\"/home/user/git/L1/T0304764/acsl_lsp/Acsl_lsp/_build/default:.\"     stdlib.c > \"stdlib.res.log\" 2> \"stdlib.err.log\"'"))
)
(rule
  (alias "stdlib.0.exec.diff")
  (enabled_if (and true))
(action (diff "../oracle/stdlib.res.oracle" "stdlib.res.log"))
)
(rule
  (alias "stdlib.0.exec.diff")
  (enabled_if (and true))
(action (diff "../oracle/stdlib.err.oracle" "stdlib.err.log"))
)
(alias (name "stdlib.diff")
  (deps (alias "stdlib.0.exec.diff"))
  (enabled_if (and true))
)
(alias (name "ptests_config")
  (deps (alias "stdlib.diff"))
  (enabled_if (and true))
)
; TEST FILE "locale.c"
(alias (name "locale.wtests")
  (deps (alias "locale.0.exec.wtests"))) ; to performs all sub-tests related to a file
(alias (name "locale.c")
  (deps (alias "locale.0.exec"))) ; to reproduce and visualize the all sub-test outputs related to a file
(rule ; TEST #0 OF TEST FILE tests/framac_libc/locale.c
  (alias "locale.0.exec.wtests")
  (targets "locale.err.log" "locale.res.log"  )
  (deps "locale.0.exec.wtests" "../oracle/locale.res.oracle" "../oracle/locale.err.oracle"  "locale.c"  (package frama-c)  )
  (enabled_if (and true))
(action (run frama-c-wtests -brief "locale.0.exec.wtests" "frama-c -check -no-autoload-plugins -add-symbolic-path=\"/home/user/git/L1/T0304764/acsl_lsp/Acsl_lsp/_build/default:.\"     locale.c > \"locale.res.log\" 2> \"locale.err.log\"" ))
)
(rule ; REPRODUCE TEST #0 OF TEST FILE "locale.c"
  (alias "locale.0.exec")
  (deps  "locale.c"  (package frama-c)   (universe))
  (enabled_if (and true))
(action (with-accepted-exit-codes 0 (system "frama-c -check -no-autoload-plugins -add-symbolic-path=\"/home/user/git/L1/T0304764/acsl_lsp/Acsl_lsp/_build/default:.\"     locale.c")))
)
(rule ; SHOW TEST COMMAND #0 OF TEST FILE "locale.c"
  (alias "locale.0.exec.show")
  (deps  "locale.c"  (package frama-c)   (universe))
  (enabled_if (and true))
(action (system "echo 'frama-c -check -no-autoload-plugins -add-symbolic-path=\"/home/user/git/L1/T0304764/acsl_lsp/Acsl_lsp/_build/default:.\"     locale.c > \"locale.res.log\" 2> \"locale.err.log\"'"))
)
(rule
  (alias "locale.0.exec.diff")
  (enabled_if (and true))
(action (diff "../oracle/locale.res.oracle" "locale.res.log"))
)
(rule
  (alias "locale.0.exec.diff")
  (enabled_if (and true))
(action (diff "../oracle/locale.err.oracle" "locale.err.log"))
)
(alias (name "locale.diff")
  (deps (alias "locale.0.exec.diff"))
  (enabled_if (and true))
)
(alias (name "ptests_config")
  (deps (alias "locale.diff"))
  (enabled_if (and true))
)
; TEST FILE "stdatomic.c"
(alias (name "stdatomic.wtests")
  (deps (alias "stdatomic.0.exec.wtests"))) ; to performs all sub-tests related to a file
(alias (name "stdatomic.c")
  (deps (alias "stdatomic.0.exec"))) ; to reproduce and visualize the all sub-test outputs related to a file
(rule ; TEST #0 OF TEST FILE tests/framac_libc/stdatomic.c
  (alias "stdatomic.0.exec.wtests")
  (targets "stdatomic.err.log" "stdatomic.res.log"  )
  (deps "stdatomic.0.exec.wtests" "../oracle/stdatomic.res.oracle" "../oracle/stdatomic.err.oracle"  "stdatomic.c"  (package frama-c)  )
  (enabled_if (and true))
(action (run frama-c-wtests -brief "stdatomic.0.exec.wtests" "frama-c -check -no-autoload-plugins -add-symbolic-path=\"/home/user/git/L1/T0304764/acsl_lsp/Acsl_lsp/_build/default:.\"     stdatomic.c > \"stdatomic.res.log\" 2> \"stdatomic.err.log\"" ))
)
(rule ; REPRODUCE TEST #0 OF TEST FILE "stdatomic.c"
  (alias "stdatomic.0.exec")
  (deps  "stdatomic.c"  (package frama-c)   (universe))
  (enabled_if (and true))
(action (with-accepted-exit-codes 0 (system "frama-c -check -no-autoload-plugins -add-symbolic-path=\"/home/user/git/L1/T0304764/acsl_lsp/Acsl_lsp/_build/default:.\"     stdatomic.c")))
)
(rule ; SHOW TEST COMMAND #0 OF TEST FILE "stdatomic.c"
  (alias "stdatomic.0.exec.show")
  (deps  "stdatomic.c"  (package frama-c)   (universe))
  (enabled_if (and true))
(action (system "echo 'frama-c -check -no-autoload-plugins -add-symbolic-path=\"/home/user/git/L1/T0304764/acsl_lsp/Acsl_lsp/_build/default:.\"     stdatomic.c > \"stdatomic.res.log\" 2> \"stdatomic.err.log\"'"))
)
(rule
  (alias "stdatomic.0.exec.diff")
  (enabled_if (and true))
(action (diff "../oracle/stdatomic.res.oracle" "stdatomic.res.log"))
)
(rule
  (alias "stdatomic.0.exec.diff")
  (enabled_if (and true))
(action (diff "../oracle/stdatomic.err.oracle" "stdatomic.err.log"))
)
(alias (name "stdatomic.diff")
  (deps (alias "stdatomic.0.exec.diff"))
  (enabled_if (and true))
)
(alias (name "ptests_config")
  (deps (alias "stdatomic.diff"))
  (enabled_if (and true))
)
; TEST FILE "__fc_runtime.c"
(alias (name "__fc_runtime.wtests")
  (deps (alias "__fc_runtime.0.exec.wtests"))) ; to performs all sub-tests related to a file
(alias (name "__fc_runtime.c")
  (deps (alias "__fc_runtime.0.exec"))) ; to reproduce and visualize the all sub-test outputs related to a file
(rule ; TEST #0 OF TEST FILE tests/framac_libc/__fc_runtime.c
  (alias "__fc_runtime.0.exec.wtests")
  (targets "__fc_runtime.err.log" "__fc_runtime.res.log"  )
  (deps "__fc_runtime.0.exec.wtests" "../oracle/__fc_runtime.res.oracle" "../oracle/__fc_runtime.err.oracle"  "__fc_runtime.c"  (package frama-c)  )
  (enabled_if (and true))
(action (run frama-c-wtests -brief "__fc_runtime.0.exec.wtests" "frama-c -check -no-autoload-plugins -add-symbolic-path=\"/home/user/git/L1/T0304764/acsl_lsp/Acsl_lsp/_build/default:.\"     __fc_runtime.c > \"__fc_runtime.res.log\" 2> \"__fc_runtime.err.log\"" ))
)
(rule ; REPRODUCE TEST #0 OF TEST FILE "__fc_runtime.c"
  (alias "__fc_runtime.0.exec")
  (deps  "__fc_runtime.c"  (package frama-c)   (universe))
  (enabled_if (and true))
(action (with-accepted-exit-codes 0 (system "frama-c -check -no-autoload-plugins -add-symbolic-path=\"/home/user/git/L1/T0304764/acsl_lsp/Acsl_lsp/_build/default:.\"     __fc_runtime.c")))
)
(rule ; SHOW TEST COMMAND #0 OF TEST FILE "__fc_runtime.c"
  (alias "__fc_runtime.0.exec.show")
  (deps  "__fc_runtime.c"  (package frama-c)   (universe))
  (enabled_if (and true))
(action (system "echo 'frama-c -check -no-autoload-plugins -add-symbolic-path=\"/home/user/git/L1/T0304764/acsl_lsp/Acsl_lsp/_build/default:.\"     __fc_runtime.c > \"__fc_runtime.res.log\" 2> \"__fc_runtime.err.log\"'"))
)
(rule
  (alias "__fc_runtime.0.exec.diff")
  (enabled_if (and true))
(action (diff "../oracle/__fc_runtime.res.oracle" "__fc_runtime.res.log"))
)
(rule
  (alias "__fc_runtime.0.exec.diff")
  (enabled_if (and true))
(action (diff "../oracle/__fc_runtime.err.oracle" "__fc_runtime.err.log"))
)
(alias (name "__fc_runtime.diff")
  (deps (alias "__fc_runtime.0.exec.diff"))
  (enabled_if (and true))
)
(alias (name "ptests_config")
  (deps (alias "__fc_runtime.diff"))
  (enabled_if (and true))
)
; TEST FILE "signal.c"
(alias (name "signal.wtests")
  (deps (alias "signal.0.exec.wtests"))) ; to performs all sub-tests related to a file
(alias (name "signal.c")
  (deps (alias "signal.0.exec"))) ; to reproduce and visualize the all sub-test outputs related to a file
(rule ; TEST #0 OF TEST FILE tests/framac_libc/signal.c
  (alias "signal.0.exec.wtests")
  (targets "signal.err.log" "signal.res.log"  )
  (deps "signal.0.exec.wtests" "../oracle/signal.res.oracle" "../oracle/signal.err.oracle"  "signal.c"  (package frama-c)  )
  (enabled_if (and true))
(action (run frama-c-wtests -brief "signal.0.exec.wtests" "frama-c -check -no-autoload-plugins -add-symbolic-path=\"/home/user/git/L1/T0304764/acsl_lsp/Acsl_lsp/_build/default:.\"     signal.c > \"signal.res.log\" 2> \"signal.err.log\"" ))
)
(rule ; REPRODUCE TEST #0 OF TEST FILE "signal.c"
  (alias "signal.0.exec")
  (deps  "signal.c"  (package frama-c)   (universe))
  (enabled_if (and true))
(action (with-accepted-exit-codes 0 (system "frama-c -check -no-autoload-plugins -add-symbolic-path=\"/home/user/git/L1/T0304764/acsl_lsp/Acsl_lsp/_build/default:.\"     signal.c")))
)
(rule ; SHOW TEST COMMAND #0 OF TEST FILE "signal.c"
  (alias "signal.0.exec.show")
  (deps  "signal.c"  (package frama-c)   (universe))
  (enabled_if (and true))
(action (system "echo 'frama-c -check -no-autoload-plugins -add-symbolic-path=\"/home/user/git/L1/T0304764/acsl_lsp/Acsl_lsp/_build/default:.\"     signal.c > \"signal.res.log\" 2> \"signal.err.log\"'"))
)
(rule
  (alias "signal.0.exec.diff")
  (enabled_if (and true))
(action (diff "../oracle/signal.res.oracle" "signal.res.log"))
)
(rule
  (alias "signal.0.exec.diff")
  (enabled_if (and true))
(action (diff "../oracle/signal.err.oracle" "signal.err.log"))
)
(alias (name "signal.diff")
  (deps (alias "signal.0.exec.diff"))
  (enabled_if (and true))
)
(alias (name "ptests_config")
  (deps (alias "signal.diff"))
  (enabled_if (and true))
)
; TEST FILE "netdb.c"
(alias (name "netdb.wtests")
  (deps (alias "netdb.0.exec.wtests"))) ; to performs all sub-tests related to a file
(alias (name "netdb.c")
  (deps (alias "netdb.0.exec"))) ; to reproduce and visualize the all sub-test outputs related to a file
(rule ; TEST #0 OF TEST FILE tests/framac_libc/netdb.c
  (alias "netdb.0.exec.wtests")
  (targets "netdb.err.log" "netdb.res.log"  )
  (deps "netdb.0.exec.wtests" "../oracle/netdb.res.oracle" "../oracle/netdb.err.oracle"  "netdb.c"  (package frama-c)  )
  (enabled_if (and true))
(action (run frama-c-wtests -brief "netdb.0.exec.wtests" "frama-c -check -no-autoload-plugins -add-symbolic-path=\"/home/user/git/L1/T0304764/acsl_lsp/Acsl_lsp/_build/default:.\"     netdb.c > \"netdb.res.log\" 2> \"netdb.err.log\"" ))
)
(rule ; REPRODUCE TEST #0 OF TEST FILE "netdb.c"
  (alias "netdb.0.exec")
  (deps  "netdb.c"  (package frama-c)   (universe))
  (enabled_if (and true))
(action (with-accepted-exit-codes 0 (system "frama-c -check -no-autoload-plugins -add-symbolic-path=\"/home/user/git/L1/T0304764/acsl_lsp/Acsl_lsp/_build/default:.\"     netdb.c")))
)
(rule ; SHOW TEST COMMAND #0 OF TEST FILE "netdb.c"
  (alias "netdb.0.exec.show")
  (deps  "netdb.c"  (package frama-c)   (universe))
  (enabled_if (and true))
(action (system "echo 'frama-c -check -no-autoload-plugins -add-symbolic-path=\"/home/user/git/L1/T0304764/acsl_lsp/Acsl_lsp/_build/default:.\"     netdb.c > \"netdb.res.log\" 2> \"netdb.err.log\"'"))
)
(rule
  (alias "netdb.0.exec.diff")
  (enabled_if (and true))
(action (diff "../oracle/netdb.res.oracle" "netdb.res.log"))
)
(rule
  (alias "netdb.0.exec.diff")
  (enabled_if (and true))
(action (diff "../oracle/netdb.err.oracle" "netdb.err.log"))
)
(alias (name "netdb.diff")
  (deps (alias "netdb.0.exec.diff"))
  (enabled_if (and true))
)
(alias (name "ptests_config")
  (deps (alias "netdb.diff"))
  (enabled_if (and true))
)
; TEST FILE "wchar.c"
(alias (name "wchar.wtests")
  (deps (alias "wchar.0.exec.wtests"))) ; to performs all sub-tests related to a file
(alias (name "wchar.c")
  (deps (alias "wchar.0.exec"))) ; to reproduce and visualize the all sub-test outputs related to a file
(rule ; TEST #0 OF TEST FILE tests/framac_libc/wchar.c
  (alias "wchar.0.exec.wtests")
  (targets "wchar.err.log" "wchar.res.log"  )
  (deps "wchar.0.exec.wtests" "../oracle/wchar.res.oracle" "../oracle/wchar.err.oracle"  "wchar.c"  (package frama-c)  )
  (enabled_if (and true))
(action (run frama-c-wtests -brief "wchar.0.exec.wtests" "frama-c -check -no-autoload-plugins -add-symbolic-path=\"/home/user/git/L1/T0304764/acsl_lsp/Acsl_lsp/_build/default:.\"     wchar.c > \"wchar.res.log\" 2> \"wchar.err.log\"" ))
)
(rule ; REPRODUCE TEST #0 OF TEST FILE "wchar.c"
  (alias "wchar.0.exec")
  (deps  "wchar.c"  (package frama-c)   (universe))
  (enabled_if (and true))
(action (with-accepted-exit-codes 0 (system "frama-c -check -no-autoload-plugins -add-symbolic-path=\"/home/user/git/L1/T0304764/acsl_lsp/Acsl_lsp/_build/default:.\"     wchar.c")))
)
(rule ; SHOW TEST COMMAND #0 OF TEST FILE "wchar.c"
  (alias "wchar.0.exec.show")
  (deps  "wchar.c"  (package frama-c)   (universe))
  (enabled_if (and true))
(action (system "echo 'frama-c -check -no-autoload-plugins -add-symbolic-path=\"/home/user/git/L1/T0304764/acsl_lsp/Acsl_lsp/_build/default:.\"     wchar.c > \"wchar.res.log\" 2> \"wchar.err.log\"'"))
)
(rule
  (alias "wchar.0.exec.diff")
  (enabled_if (and true))
(action (diff "../oracle/wchar.res.oracle" "wchar.res.log"))
)
(rule
  (alias "wchar.0.exec.diff")
  (enabled_if (and true))
(action (diff "../oracle/wchar.err.oracle" "wchar.err.log"))
)
(alias (name "wchar.diff")
  (deps (alias "wchar.0.exec.diff"))
  (enabled_if (and true))
)
(alias (name "ptests_config")
  (deps (alias "wchar.diff"))
  (enabled_if (and true))
)
; TEST FILE "inttypes.c"
(alias (name "inttypes.wtests")
  (deps (alias "inttypes.0.exec.wtests"))) ; to performs all sub-tests related to a file
(alias (name "inttypes.c")
  (deps (alias "inttypes.0.exec"))) ; to reproduce and visualize the all sub-test outputs related to a file
(rule ; TEST #0 OF TEST FILE tests/framac_libc/inttypes.c
  (alias "inttypes.0.exec.wtests")
  (targets "inttypes.err.log" "inttypes.res.log"  )
  (deps "inttypes.0.exec.wtests" "../oracle/inttypes.res.oracle" "../oracle/inttypes.err.oracle"  "inttypes.c"  (package frama-c)  )
  (enabled_if (and true))
(action (run frama-c-wtests -brief "inttypes.0.exec.wtests" "frama-c -check -no-autoload-plugins -add-symbolic-path=\"/home/user/git/L1/T0304764/acsl_lsp/Acsl_lsp/_build/default:.\"     inttypes.c > \"inttypes.res.log\" 2> \"inttypes.err.log\"" ))
)
(rule ; REPRODUCE TEST #0 OF TEST FILE "inttypes.c"
  (alias "inttypes.0.exec")
  (deps  "inttypes.c"  (package frama-c)   (universe))
  (enabled_if (and true))
(action (with-accepted-exit-codes 0 (system "frama-c -check -no-autoload-plugins -add-symbolic-path=\"/home/user/git/L1/T0304764/acsl_lsp/Acsl_lsp/_build/default:.\"     inttypes.c")))
)
(rule ; SHOW TEST COMMAND #0 OF TEST FILE "inttypes.c"
  (alias "inttypes.0.exec.show")
  (deps  "inttypes.c"  (package frama-c)   (universe))
  (enabled_if (and true))
(action (system "echo 'frama-c -check -no-autoload-plugins -add-symbolic-path=\"/home/user/git/L1/T0304764/acsl_lsp/Acsl_lsp/_build/default:.\"     inttypes.c > \"inttypes.res.log\" 2> \"inttypes.err.log\"'"))
)
(rule
  (alias "inttypes.0.exec.diff")
  (enabled_if (and true))
(action (diff "../oracle/inttypes.res.oracle" "inttypes.res.log"))
)
(rule
  (alias "inttypes.0.exec.diff")
  (enabled_if (and true))
(action (diff "../oracle/inttypes.err.oracle" "inttypes.err.log"))
)
(alias (name "inttypes.diff")
  (deps (alias "inttypes.0.exec.diff"))
  (enabled_if (and true))
)
(alias (name "ptests_config")
  (deps (alias "inttypes.diff"))
  (enabled_if (and true))
)
; TEST FILE "ctype.c"
(alias (name "ctype.wtests")
  (deps (alias "ctype.0.exec.wtests"))) ; to performs all sub-tests related to a file
(alias (name "ctype.c")
  (deps (alias "ctype.0.exec"))) ; to reproduce and visualize the all sub-test outputs related to a file
(rule ; TEST #0 OF TEST FILE tests/framac_libc/ctype.c
  (alias "ctype.0.exec.wtests")
  (targets "ctype.err.log" "ctype.res.log"  )
  (deps "ctype.0.exec.wtests" "../oracle/ctype.res.oracle" "../oracle/ctype.err.oracle"  "ctype.c"  (package frama-c)  )
  (enabled_if (and true))
(action (run frama-c-wtests -brief "ctype.0.exec.wtests" "frama-c -check -no-autoload-plugins -add-symbolic-path=\"/home/user/git/L1/T0304764/acsl_lsp/Acsl_lsp/_build/default:.\"     ctype.c > \"ctype.res.log\" 2> \"ctype.err.log\"" ))
)
(rule ; REPRODUCE TEST #0 OF TEST FILE "ctype.c"
  (alias "ctype.0.exec")
  (deps  "ctype.c"  (package frama-c)   (universe))
  (enabled_if (and true))
(action (with-accepted-exit-codes 0 (system "frama-c -check -no-autoload-plugins -add-symbolic-path=\"/home/user/git/L1/T0304764/acsl_lsp/Acsl_lsp/_build/default:.\"     ctype.c")))
)
(rule ; SHOW TEST COMMAND #0 OF TEST FILE "ctype.c"
  (alias "ctype.0.exec.show")
  (deps  "ctype.c"  (package frama-c)   (universe))
  (enabled_if (and true))
(action (system "echo 'frama-c -check -no-autoload-plugins -add-symbolic-path=\"/home/user/git/L1/T0304764/acsl_lsp/Acsl_lsp/_build/default:.\"     ctype.c > \"ctype.res.log\" 2> \"ctype.err.log\"'"))
)
(rule
  (alias "ctype.0.exec.diff")
  (enabled_if (and true))
(action (diff "../oracle/ctype.res.oracle" "ctype.res.log"))
)
(rule
  (alias "ctype.0.exec.diff")
  (enabled_if (and true))
(action (diff "../oracle/ctype.err.oracle" "ctype.err.log"))
)
(alias (name "ctype.diff")
  (deps (alias "ctype.0.exec.diff"))
  (enabled_if (and true))
)
(alias (name "ptests_config")
  (deps (alias "ctype.diff"))
  (enabled_if (and true))
)
; TEST FILE "unistd.c"
(alias (name "unistd.wtests")
  (deps (alias "unistd.0.exec.wtests"))) ; to performs all sub-tests related to a file
(alias (name "unistd.c")
  (deps (alias "unistd.0.exec"))) ; to reproduce and visualize the all sub-test outputs related to a file
(rule ; TEST #0 OF TEST FILE tests/framac_libc/unistd.c
  (alias "unistd.0.exec.wtests")
  (targets "unistd.err.log" "unistd.res.log"  )
  (deps "unistd.0.exec.wtests" "../oracle/unistd.res.oracle" "../oracle/unistd.err.oracle"  "unistd.c"  (package frama-c)  )
  (enabled_if (and true))
(action (run frama-c-wtests -brief "unistd.0.exec.wtests" "frama-c -check -no-autoload-plugins -add-symbolic-path=\"/home/user/git/L1/T0304764/acsl_lsp/Acsl_lsp/_build/default:.\"     unistd.c > \"unistd.res.log\" 2> \"unistd.err.log\"" ))
)
(rule ; REPRODUCE TEST #0 OF TEST FILE "unistd.c"
  (alias "unistd.0.exec")
  (deps  "unistd.c"  (package frama-c)   (universe))
  (enabled_if (and true))
(action (with-accepted-exit-codes 0 (system "frama-c -check -no-autoload-plugins -add-symbolic-path=\"/home/user/git/L1/T0304764/acsl_lsp/Acsl_lsp/_build/default:.\"     unistd.c")))
)
(rule ; SHOW TEST COMMAND #0 OF TEST FILE "unistd.c"
  (alias "unistd.0.exec.show")
  (deps  "unistd.c"  (package frama-c)   (universe))
  (enabled_if (and true))
(action (system "echo 'frama-c -check -no-autoload-plugins -add-symbolic-path=\"/home/user/git/L1/T0304764/acsl_lsp/Acsl_lsp/_build/default:.\"     unistd.c > \"unistd.res.log\" 2> \"unistd.err.log\"'"))
)
(rule
  (alias "unistd.0.exec.diff")
  (enabled_if (and true))
(action (diff "../oracle/unistd.res.oracle" "unistd.res.log"))
)
(rule
  (alias "unistd.0.exec.diff")
  (enabled_if (and true))
(action (diff "../oracle/unistd.err.oracle" "unistd.err.log"))
)
(alias (name "unistd.diff")
  (deps (alias "unistd.0.exec.diff"))
  (enabled_if (and true))
)
(alias (name "ptests_config")
  (deps (alias "unistd.diff"))
  (enabled_if (and true))
)
; TEST FILE "stdio.c"
(alias (name "stdio.wtests")
  (deps (alias "stdio.0.exec.wtests"))) ; to performs all sub-tests related to a file
(alias (name "stdio.c")
  (deps (alias "stdio.0.exec"))) ; to reproduce and visualize the all sub-test outputs related to a file
(rule ; TEST #0 OF TEST FILE tests/framac_libc/stdio.c
  (alias "stdio.0.exec.wtests")
  (targets "stdio.err.log" "stdio.res.log"  )
  (deps "stdio.0.exec.wtests" "../oracle/stdio.res.oracle" "../oracle/stdio.err.oracle"  "stdio.c"  (package frama-c)  )
  (enabled_if (and true))
(action (run frama-c-wtests -brief "stdio.0.exec.wtests" "frama-c -check -no-autoload-plugins -add-symbolic-path=\"/home/user/git/L1/T0304764/acsl_lsp/Acsl_lsp/_build/default:.\"     stdio.c > \"stdio.res.log\" 2> \"stdio.err.log\"" ))
)
(rule ; REPRODUCE TEST #0 OF TEST FILE "stdio.c"
  (alias "stdio.0.exec")
  (deps  "stdio.c"  (package frama-c)   (universe))
  (enabled_if (and true))
(action (with-accepted-exit-codes 0 (system "frama-c -check -no-autoload-plugins -add-symbolic-path=\"/home/user/git/L1/T0304764/acsl_lsp/Acsl_lsp/_build/default:.\"     stdio.c")))
)
(rule ; SHOW TEST COMMAND #0 OF TEST FILE "stdio.c"
  (alias "stdio.0.exec.show")
  (deps  "stdio.c"  (package frama-c)   (universe))
  (enabled_if (and true))
(action (system "echo 'frama-c -check -no-autoload-plugins -add-symbolic-path=\"/home/user/git/L1/T0304764/acsl_lsp/Acsl_lsp/_build/default:.\"     stdio.c > \"stdio.res.log\" 2> \"stdio.err.log\"'"))
)
(rule
  (alias "stdio.0.exec.diff")
  (enabled_if (and true))
(action (diff "../oracle/stdio.res.oracle" "stdio.res.log"))
)
(rule
  (alias "stdio.0.exec.diff")
  (enabled_if (and true))
(action (diff "../oracle/stdio.err.oracle" "stdio.err.log"))
)
(alias (name "stdio.diff")
  (deps (alias "stdio.0.exec.diff"))
  (enabled_if (and true))
)
(alias (name "ptests_config")
  (deps (alias "stdio.diff"))
  (enabled_if (and true))
)
; TEST FILE "time.c"
(alias (name "time.wtests")
  (deps (alias "time.0.exec.wtests"))) ; to performs all sub-tests related to a file
(alias (name "time.c")
  (deps (alias "time.0.exec"))) ; to reproduce and visualize the all sub-test outputs related to a file
(rule ; TEST #0 OF TEST FILE tests/framac_libc/time.c
  (alias "time.0.exec.wtests")
  (targets "time.err.log" "time.res.log"  )
  (deps "time.0.exec.wtests" "../oracle/time.res.oracle" "../oracle/time.err.oracle"  "time.c"  (package frama-c)  )
  (enabled_if (and true))
(action (run frama-c-wtests -brief "time.0.exec.wtests" "frama-c -check -no-autoload-plugins -add-symbolic-path=\"/home/user/git/L1/T0304764/acsl_lsp/Acsl_lsp/_build/default:.\"     time.c > \"time.res.log\" 2> \"time.err.log\"" ))
)
(rule ; REPRODUCE TEST #0 OF TEST FILE "time.c"
  (alias "time.0.exec")
  (deps  "time.c"  (package frama-c)   (universe))
  (enabled_if (and true))
(action (with-accepted-exit-codes 0 (system "frama-c -check -no-autoload-plugins -add-symbolic-path=\"/home/user/git/L1/T0304764/acsl_lsp/Acsl_lsp/_build/default:.\"     time.c")))
)
(rule ; SHOW TEST COMMAND #0 OF TEST FILE "time.c"
  (alias "time.0.exec.show")
  (deps  "time.c"  (package frama-c)   (universe))
  (enabled_if (and true))
(action (system "echo 'frama-c -check -no-autoload-plugins -add-symbolic-path=\"/home/user/git/L1/T0304764/acsl_lsp/Acsl_lsp/_build/default:.\"     time.c > \"time.res.log\" 2> \"time.err.log\"'"))
)
(rule
  (alias "time.0.exec.diff")
  (enabled_if (and true))
(action (diff "../oracle/time.res.oracle" "time.res.log"))
)
(rule
  (alias "time.0.exec.diff")
  (enabled_if (and true))
(action (diff "../oracle/time.err.oracle" "time.err.log"))
)
(alias (name "time.diff")
  (deps (alias "time.0.exec.diff"))
  (enabled_if (and true))
)
(alias (name "ptests_config")
  (deps (alias "time.diff"))
  (enabled_if (and true))
)
; TEST FILE "__fc_builtin.c"
(alias (name "__fc_builtin.wtests")
  (deps (alias "__fc_builtin.0.exec.wtests"))) ; to performs all sub-tests related to a file
(alias (name "__fc_builtin.c")
  (deps (alias "__fc_builtin.0.exec"))) ; to reproduce and visualize the all sub-test outputs related to a file
(rule ; TEST #0 OF TEST FILE tests/framac_libc/__fc_builtin.c
  (alias "__fc_builtin.0.exec.wtests")
  (targets "__fc_builtin.err.log" "__fc_builtin.res.log"  )
  (deps "__fc_builtin.0.exec.wtests" "../oracle/__fc_builtin.res.oracle" "../oracle/__fc_builtin.err.oracle"  "__fc_builtin.c"  (package frama-c)  )
  (enabled_if (and true))
(action (run frama-c-wtests -brief "__fc_builtin.0.exec.wtests" "frama-c -check -no-autoload-plugins -add-symbolic-path=\"/home/user/git/L1/T0304764/acsl_lsp/Acsl_lsp/_build/default:.\"     __fc_builtin.c > \"__fc_builtin.res.log\" 2> \"__fc_builtin.err.log\"" ))
)
(rule ; REPRODUCE TEST #0 OF TEST FILE "__fc_builtin.c"
  (alias "__fc_builtin.0.exec")
  (deps  "__fc_builtin.c"  (package frama-c)   (universe))
  (enabled_if (and true))
(action (with-accepted-exit-codes 0 (system "frama-c -check -no-autoload-plugins -add-symbolic-path=\"/home/user/git/L1/T0304764/acsl_lsp/Acsl_lsp/_build/default:.\"     __fc_builtin.c")))
)
(rule ; SHOW TEST COMMAND #0 OF TEST FILE "__fc_builtin.c"
  (alias "__fc_builtin.0.exec.show")
  (deps  "__fc_builtin.c"  (package frama-c)   (universe))
  (enabled_if (and true))
(action (system "echo 'frama-c -check -no-autoload-plugins -add-symbolic-path=\"/home/user/git/L1/T0304764/acsl_lsp/Acsl_lsp/_build/default:.\"     __fc_builtin.c > \"__fc_builtin.res.log\" 2> \"__fc_builtin.err.log\"'"))
)
(rule
  (alias "__fc_builtin.0.exec.diff")
  (enabled_if (and true))
(action (diff "../oracle/__fc_builtin.res.oracle" "__fc_builtin.res.log"))
)
(rule
  (alias "__fc_builtin.0.exec.diff")
  (enabled_if (and true))
(action (diff "../oracle/__fc_builtin.err.oracle" "__fc_builtin.err.log"))
)
(alias (name "__fc_builtin.diff")
  (deps (alias "__fc_builtin.0.exec.diff"))
  (enabled_if (and true))
)
(alias (name "ptests_config")
  (deps (alias "__fc_builtin.diff"))
  (enabled_if (and true))
)
; TEST FILE "fenv.c"
(alias (name "fenv.wtests")
  (deps (alias "fenv.0.exec.wtests"))) ; to performs all sub-tests related to a file
(alias (name "fenv.c")
  (deps (alias "fenv.0.exec"))) ; to reproduce and visualize the all sub-test outputs related to a file
(rule ; TEST #0 OF TEST FILE tests/framac_libc/fenv.c
  (alias "fenv.0.exec.wtests")
  (targets "fenv.err.log" "fenv.res.log"  )
  (deps "fenv.0.exec.wtests" "../oracle/fenv.res.oracle" "../oracle/fenv.err.oracle"  "fenv.c"  (package frama-c)  )
  (enabled_if (and true))
(action (run frama-c-wtests -brief "fenv.0.exec.wtests" "frama-c -check -no-autoload-plugins -add-symbolic-path=\"/home/user/git/L1/T0304764/acsl_lsp/Acsl_lsp/_build/default:.\"     fenv.c > \"fenv.res.log\" 2> \"fenv.err.log\"" ))
)
(rule ; REPRODUCE TEST #0 OF TEST FILE "fenv.c"
  (alias "fenv.0.exec")
  (deps  "fenv.c"  (package frama-c)   (universe))
  (enabled_if (and true))
(action (with-accepted-exit-codes 0 (system "frama-c -check -no-autoload-plugins -add-symbolic-path=\"/home/user/git/L1/T0304764/acsl_lsp/Acsl_lsp/_build/default:.\"     fenv.c")))
)
(rule ; SHOW TEST COMMAND #0 OF TEST FILE "fenv.c"
  (alias "fenv.0.exec.show")
  (deps  "fenv.c"  (package frama-c)   (universe))
  (enabled_if (and true))
(action (system "echo 'frama-c -check -no-autoload-plugins -add-symbolic-path=\"/home/user/git/L1/T0304764/acsl_lsp/Acsl_lsp/_build/default:.\"     fenv.c > \"fenv.res.log\" 2> \"fenv.err.log\"'"))
)
(rule
  (alias "fenv.0.exec.diff")
  (enabled_if (and true))
(action (diff "../oracle/fenv.res.oracle" "fenv.res.log"))
)
(rule
  (alias "fenv.0.exec.diff")
  (enabled_if (and true))
(action (diff "../oracle/fenv.err.oracle" "fenv.err.log"))
)
(alias (name "fenv.diff")
  (deps (alias "fenv.0.exec.diff"))
  (enabled_if (and true))
)
(alias (name "ptests_config")
  (deps (alias "fenv.diff"))
  (enabled_if (and true))
)
; TEST FILE "string.c"
(alias (name "string.wtests")
  (deps (alias "string.0.exec.wtests"))) ; to performs all sub-tests related to a file
(alias (name "string.c")
  (deps (alias "string.0.exec"))) ; to reproduce and visualize the all sub-test outputs related to a file
(rule ; TEST #0 OF TEST FILE tests/framac_libc/string.c
  (alias "string.0.exec.wtests")
  (targets "string.err.log" "string.res.log"  )
  (deps "string.0.exec.wtests" "../oracle/string.res.oracle" "../oracle/string.err.oracle"  "string.c"  (package frama-c)  )
  (enabled_if (and true))
(action (run frama-c-wtests -brief "string.0.exec.wtests" "frama-c -check -no-autoload-plugins -add-symbolic-path=\"/home/user/git/L1/T0304764/acsl_lsp/Acsl_lsp/_build/default:.\"     string.c > \"string.res.log\" 2> \"string.err.log\"" ))
)
(rule ; REPRODUCE TEST #0 OF TEST FILE "string.c"
  (alias "string.0.exec")
  (deps  "string.c"  (package frama-c)   (universe))
  (enabled_if (and true))
(action (with-accepted-exit-codes 0 (system "frama-c -check -no-autoload-plugins -add-symbolic-path=\"/home/user/git/L1/T0304764/acsl_lsp/Acsl_lsp/_build/default:.\"     string.c")))
)
(rule ; SHOW TEST COMMAND #0 OF TEST FILE "string.c"
  (alias "string.0.exec.show")
  (deps  "string.c"  (package frama-c)   (universe))
  (enabled_if (and true))
(action (system "echo 'frama-c -check -no-autoload-plugins -add-symbolic-path=\"/home/user/git/L1/T0304764/acsl_lsp/Acsl_lsp/_build/default:.\"     string.c > \"string.res.log\" 2> \"string.err.log\"'"))
)
(rule
  (alias "string.0.exec.diff")
  (enabled_if (and true))
(action (diff "../oracle/string.res.oracle" "string.res.log"))
)
(rule
  (alias "string.0.exec.diff")
  (enabled_if (and true))
(action (diff "../oracle/string.err.oracle" "string.err.log"))
)
(alias (name "string.diff")
  (deps (alias "string.0.exec.diff"))
  (enabled_if (and true))
)
(alias (name "ptests_config")
  (deps (alias "string.diff"))
  (enabled_if (and true))
)
; TEST FILE "assert.c"
(alias (name "assert.wtests")
  (deps (alias "assert.0.exec.wtests"))) ; to performs all sub-tests related to a file
(alias (name "assert.c")
  (deps (alias "assert.0.exec"))) ; to reproduce and visualize the all sub-test outputs related to a file
(rule ; TEST #0 OF TEST FILE tests/framac_libc/assert.c
  (alias "assert.0.exec.wtests")
  (targets "assert.err.log" "assert.res.log"  )
  (deps "assert.0.exec.wtests" "../oracle/assert.res.oracle" "../oracle/assert.err.oracle"  "assert.c"  (package frama-c)  )
  (enabled_if (and true))
(action (run frama-c-wtests -brief "assert.0.exec.wtests" "frama-c -check -no-autoload-plugins -add-symbolic-path=\"/home/user/git/L1/T0304764/acsl_lsp/Acsl_lsp/_build/default:.\"     assert.c > \"assert.res.log\" 2> \"assert.err.log\"" ))
)
(rule ; REPRODUCE TEST #0 OF TEST FILE "assert.c"
  (alias "assert.0.exec")
  (deps  "assert.c"  (package frama-c)   (universe))
  (enabled_if (and true))
(action (with-accepted-exit-codes 0 (system "frama-c -check -no-autoload-plugins -add-symbolic-path=\"/home/user/git/L1/T0304764/acsl_lsp/Acsl_lsp/_build/default:.\"     assert.c")))
)
(rule ; SHOW TEST COMMAND #0 OF TEST FILE "assert.c"
  (alias "assert.0.exec.show")
  (deps  "assert.c"  (package frama-c)   (universe))
  (enabled_if (and true))
(action (system "echo 'frama-c -check -no-autoload-plugins -add-symbolic-path=\"/home/user/git/L1/T0304764/acsl_lsp/Acsl_lsp/_build/default:.\"     assert.c > \"assert.res.log\" 2> \"assert.err.log\"'"))
)
(rule
  (alias "assert.0.exec.diff")
  (enabled_if (and true))
(action (diff "../oracle/assert.res.oracle" "assert.res.log"))
)
(rule
  (alias "assert.0.exec.diff")
  (enabled_if (and true))
(action (diff "../oracle/assert.err.oracle" "assert.err.log"))
)
(alias (name "assert.diff")
  (deps (alias "assert.0.exec.diff"))
  (enabled_if (and true))
)
(alias (name "ptests_config")
  (deps (alias "assert.diff"))
  (enabled_if (and true))
)
; TEST FILE "argz.c"
(alias (name "argz.wtests")
  (deps (alias "argz.0.exec.wtests"))) ; to performs all sub-tests related to a file
(alias (name "argz.c")
  (deps (alias "argz.0.exec"))) ; to reproduce and visualize the all sub-test outputs related to a file
(rule ; TEST #0 OF TEST FILE tests/framac_libc/argz.c
  (alias "argz.0.exec.wtests")
  (targets "argz.err.log" "argz.res.log"  )
  (deps "argz.0.exec.wtests" "../oracle/argz.res.oracle" "../oracle/argz.err.oracle"  "argz.c"  (package frama-c)  )
  (enabled_if (and true))
(action (run frama-c-wtests -brief "argz.0.exec.wtests" "frama-c -check -no-autoload-plugins -add-symbolic-path=\"/home/user/git/L1/T0304764/acsl_lsp/Acsl_lsp/_build/default:.\"     argz.c > \"argz.res.log\" 2> \"argz.err.log\"" ))
)
(rule ; REPRODUCE TEST #0 OF TEST FILE "argz.c"
  (alias "argz.0.exec")
  (deps  "argz.c"  (package frama-c)   (universe))
  (enabled_if (and true))
(action (with-accepted-exit-codes 0 (system "frama-c -check -no-autoload-plugins -add-symbolic-path=\"/home/user/git/L1/T0304764/acsl_lsp/Acsl_lsp/_build/default:.\"     argz.c")))
)
(rule ; SHOW TEST COMMAND #0 OF TEST FILE "argz.c"
  (alias "argz.0.exec.show")
  (deps  "argz.c"  (package frama-c)   (universe))
  (enabled_if (and true))
(action (system "echo 'frama-c -check -no-autoload-plugins -add-symbolic-path=\"/home/user/git/L1/T0304764/acsl_lsp/Acsl_lsp/_build/default:.\"     argz.c > \"argz.res.log\" 2> \"argz.err.log\"'"))
)
(rule
  (alias "argz.0.exec.diff")
  (enabled_if (and true))
(action (diff "../oracle/argz.res.oracle" "argz.res.log"))
)
(rule
  (alias "argz.0.exec.diff")
  (enabled_if (and true))
(action (diff "../oracle/argz.err.oracle" "argz.err.log"))
)
(alias (name "argz.diff")
  (deps (alias "argz.0.exec.diff"))
  (enabled_if (and true))
)
(alias (name "ptests_config")
  (deps (alias "argz.diff"))
  (enabled_if (and true))
)
; TEST FILE "pwd.c"
(alias (name "pwd.wtests")
  (deps (alias "pwd.0.exec.wtests"))) ; to performs all sub-tests related to a file
(alias (name "pwd.c")
  (deps (alias "pwd.0.exec"))) ; to reproduce and visualize the all sub-test outputs related to a file
(rule ; TEST #0 OF TEST FILE tests/framac_libc/pwd.c
  (alias "pwd.0.exec.wtests")
  (targets "pwd.err.log" "pwd.res.log"  )
  (deps "pwd.0.exec.wtests" "../oracle/pwd.res.oracle" "../oracle/pwd.err.oracle"  "pwd.c"  (package frama-c)  )
  (enabled_if (and true))
(action (run frama-c-wtests -brief "pwd.0.exec.wtests" "frama-c -check -no-autoload-plugins -add-symbolic-path=\"/home/user/git/L1/T0304764/acsl_lsp/Acsl_lsp/_build/default:.\"     pwd.c > \"pwd.res.log\" 2> \"pwd.err.log\"" ))
)
(rule ; REPRODUCE TEST #0 OF TEST FILE "pwd.c"
  (alias "pwd.0.exec")
  (deps  "pwd.c"  (package frama-c)   (universe))
  (enabled_if (and true))
(action (with-accepted-exit-codes 0 (system "frama-c -check -no-autoload-plugins -add-symbolic-path=\"/home/user/git/L1/T0304764/acsl_lsp/Acsl_lsp/_build/default:.\"     pwd.c")))
)
(rule ; SHOW TEST COMMAND #0 OF TEST FILE "pwd.c"
  (alias "pwd.0.exec.show")
  (deps  "pwd.c"  (package frama-c)   (universe))
  (enabled_if (and true))
(action (system "echo 'frama-c -check -no-autoload-plugins -add-symbolic-path=\"/home/user/git/L1/T0304764/acsl_lsp/Acsl_lsp/_build/default:.\"     pwd.c > \"pwd.res.log\" 2> \"pwd.err.log\"'"))
)
(rule
  (alias "pwd.0.exec.diff")
  (enabled_if (and true))
(action (diff "../oracle/pwd.res.oracle" "pwd.res.log"))
)
(rule
  (alias "pwd.0.exec.diff")
  (enabled_if (and true))
(action (diff "../oracle/pwd.err.oracle" "pwd.err.log"))
)
(alias (name "pwd.diff")
  (deps (alias "pwd.0.exec.diff"))
  (enabled_if (and true))
)
(alias (name "ptests_config")
  (deps (alias "pwd.diff"))
  (enabled_if (and true))
)
; TEST FILE "math.c"
(alias (name "math.wtests")
  (deps (alias "math.0.exec.wtests"))) ; to performs all sub-tests related to a file
(alias (name "math.c")
  (deps (alias "math.0.exec"))) ; to reproduce and visualize the all sub-test outputs related to a file
(rule ; TEST #0 OF TEST FILE tests/framac_libc/math.c
  (alias "math.0.exec.wtests")
  (targets "math.err.log" "math.res.log"  )
  (deps "math.0.exec.wtests" "../oracle/math.res.oracle" "../oracle/math.err.oracle"  "math.c"  (package frama-c)  )
  (enabled_if (and true))
(action (run frama-c-wtests -brief "math.0.exec.wtests" "frama-c -check -no-autoload-plugins -add-symbolic-path=\"/home/user/git/L1/T0304764/acsl_lsp/Acsl_lsp/_build/default:.\"     math.c > \"math.res.log\" 2> \"math.err.log\"" ))
)
(rule ; REPRODUCE TEST #0 OF TEST FILE "math.c"
  (alias "math.0.exec")
  (deps  "math.c"  (package frama-c)   (universe))
  (enabled_if (and true))
(action (with-accepted-exit-codes 0 (system "frama-c -check -no-autoload-plugins -add-symbolic-path=\"/home/user/git/L1/T0304764/acsl_lsp/Acsl_lsp/_build/default:.\"     math.c")))
)
(rule ; SHOW TEST COMMAND #0 OF TEST FILE "math.c"
  (alias "math.0.exec.show")
  (deps  "math.c"  (package frama-c)   (universe))
  (enabled_if (and true))
(action (system "echo 'frama-c -check -no-autoload-plugins -add-symbolic-path=\"/home/user/git/L1/T0304764/acsl_lsp/Acsl_lsp/_build/default:.\"     math.c > \"math.res.log\" 2> \"math.err.log\"'"))
)
(rule
  (alias "math.0.exec.diff")
  (enabled_if (and true))
(action (diff "../oracle/math.res.oracle" "math.res.log"))
)
(rule
  (alias "math.0.exec.diff")
  (enabled_if (and true))
(action (diff "../oracle/math.err.oracle" "math.err.log"))
)
(alias (name "math.diff")
  (deps (alias "math.0.exec.diff"))
  (enabled_if (and true))
)
(alias (name "ptests_config")
  (deps (alias "math.diff"))
  (enabled_if (and true))
)
; TEST FILE "glob.c"
(alias (name "glob.wtests")
  (deps (alias "glob.0.exec.wtests"))) ; to performs all sub-tests related to a file
(alias (name "glob.c")
  (deps (alias "glob.0.exec"))) ; to reproduce and visualize the all sub-test outputs related to a file
(rule ; TEST #0 OF TEST FILE tests/framac_libc/glob.c
  (alias "glob.0.exec.wtests")
  (targets "glob.err.log" "glob.res.log"  )
  (deps "glob.0.exec.wtests" "../oracle/glob.res.oracle" "../oracle/glob.err.oracle"  "glob.c"  (package frama-c)  )
  (enabled_if (and true))
(action (run frama-c-wtests -brief "glob.0.exec.wtests" "frama-c -check -no-autoload-plugins -add-symbolic-path=\"/home/user/git/L1/T0304764/acsl_lsp/Acsl_lsp/_build/default:.\"     glob.c > \"glob.res.log\" 2> \"glob.err.log\"" ))
)
(rule ; REPRODUCE TEST #0 OF TEST FILE "glob.c"
  (alias "glob.0.exec")
  (deps  "glob.c"  (package frama-c)   (universe))
  (enabled_if (and true))
(action (with-accepted-exit-codes 0 (system "frama-c -check -no-autoload-plugins -add-symbolic-path=\"/home/user/git/L1/T0304764/acsl_lsp/Acsl_lsp/_build/default:.\"     glob.c")))
)
(rule ; SHOW TEST COMMAND #0 OF TEST FILE "glob.c"
  (alias "glob.0.exec.show")
  (deps  "glob.c"  (package frama-c)   (universe))
  (enabled_if (and true))
(action (system "echo 'frama-c -check -no-autoload-plugins -add-symbolic-path=\"/home/user/git/L1/T0304764/acsl_lsp/Acsl_lsp/_build/default:.\"     glob.c > \"glob.res.log\" 2> \"glob.err.log\"'"))
)
(rule
  (alias "glob.0.exec.diff")
  (enabled_if (and true))
(action (diff "../oracle/glob.res.oracle" "glob.res.log"))
)
(rule
  (alias "glob.0.exec.diff")
  (enabled_if (and true))
(action (diff "../oracle/glob.err.oracle" "glob.err.log"))
)
(alias (name "glob.diff")
  (deps (alias "glob.0.exec.diff"))
  (enabled_if (and true))
)
(alias (name "ptests_config")
  (deps (alias "glob.diff"))
  (enabled_if (and true))
)

