lib: [
  "_build/install/default/lib/frama-c-my_plugin/META"
  "_build/install/default/lib/frama-c-my_plugin/core/my_plugin_lib.a" {"core/my_plugin_lib.a"}
  "_build/install/default/lib/frama-c-my_plugin/core/my_plugin_lib.cma" {"core/my_plugin_lib.cma"}
  "_build/install/default/lib/frama-c-my_plugin/core/my_plugin_lib.cmi" {"core/my_plugin_lib.cmi"}
  "_build/install/default/lib/frama-c-my_plugin/core/my_plugin_lib.cmt" {"core/my_plugin_lib.cmt"}
  "_build/install/default/lib/frama-c-my_plugin/core/my_plugin_lib.cmx" {"core/my_plugin_lib.cmx"}
  "_build/install/default/lib/frama-c-my_plugin/core/my_plugin_lib.cmxa" {"core/my_plugin_lib.cmxa"}
  "_build/install/default/lib/frama-c-my_plugin/core/my_plugin_lib.ml" {"core/my_plugin_lib.ml"}
  "_build/install/default/lib/frama-c-my_plugin/dune-package"
  "_build/install/default/lib/frama-c-my_plugin/opam"
]
lib_root: [
  "_build/install/default/lib/frama-c/plugins/my_plugin/META" {"frama-c/plugins/my_plugin/META"}
]
libexec: [
  "_build/install/default/lib/frama-c-my_plugin/core/my_plugin_lib.cmxs" {"core/my_plugin_lib.cmxs"}
]
bin: [
  "_build/install/default/bin/run.ml"
]
