lib: [
  "_build/install/default/lib/frama-c-acsl_lsp/META"
  "_build/install/default/lib/frama-c-acsl_lsp/core/acsl_lsp.a" {"core/acsl_lsp.a"}
  "_build/install/default/lib/frama-c-acsl_lsp/core/acsl_lsp.cma" {"core/acsl_lsp.cma"}
  "_build/install/default/lib/frama-c-acsl_lsp/core/acsl_lsp.cmi" {"core/acsl_lsp.cmi"}
  "_build/install/default/lib/frama-c-acsl_lsp/core/acsl_lsp.cmt" {"core/acsl_lsp.cmt"}
  "_build/install/default/lib/frama-c-acsl_lsp/core/acsl_lsp.cmx" {"core/acsl_lsp.cmx"}
  "_build/install/default/lib/frama-c-acsl_lsp/core/acsl_lsp.cmxa" {"core/acsl_lsp.cmxa"}
  "_build/install/default/lib/frama-c-acsl_lsp/core/acsl_lsp.ml" {"core/acsl_lsp.ml"}
  "_build/install/default/lib/frama-c-acsl_lsp/dune-package"
  "_build/install/default/lib/frama-c-acsl_lsp/opam"
]
lib_root: [
  "_build/install/default/lib/frama-c/plugins/acsl_lsp/META" {"frama-c/plugins/acsl_lsp/META"}
]
libexec: [
  "_build/install/default/lib/frama-c-acsl_lsp/core/acsl_lsp.cmxs" {"core/acsl_lsp.cmxs"}
]
bin: [
  "_build/install/default/bin/Acsl_lsp"
]
