(rule
	(alias frama-c-configure)
	(deps (universe))
	(action (progn
			(echo "my_plugin:" %{lib-available:frama-my_plugin.core} "\n")
			(echo " - Frama-C:" %{lib-available:frama-c.kernel} "\n")
		)
	)
)

(include_subdirs qualified)

(library
	(name my_plugin_lib)
	(public_name frama-c-my_plugin.core)
	(flags -open Frama_c_kernel :standard)
	(libraries 
		frama-c.kernel
	)
)


(plugin
	(name my_plugin)
	(libraries frama-c-my_plugin.core)
	(site (frama-c plugins))
)
