(rule
	(alias frama-c-configure)
	(deps (universe))
	(action (progn
			(echo "acsl_lsp:" %{lib-available:frama-acsl_lsp.core} "\n")
			(echo " - Frama-C:" %{lib-available:frama-c.kernel} "\n")
		)
	)
)

(include_subdirs unqualified)

(library
	(name acsl_lsp_lib)
	(public_name acsl-lsp.core)
	(flags -open Frama_c_kernel :standard -warn-error "-unused-value-declaration")
	(libraries 
		frama-c.kernel
	)
)


(plugin
	(name acsl_lsp)
	(libraries acsl-lsp.core)
	(site (frama-c plugins))
)

