(lang dune 3.7)
(using dune_site 0.1)

(name frama-c-acsl_lsp)

;(generate_opam_files true)

; (source
; (github username/reponame))

; (authors "auteurs")

;(maintainers "Maintainer Name")

;(license LICENSE)

;(documentation https://url/to/documentation)

(package
 (name frama-c-acsl_lsp)
 (synopsis "Language Server Protocol support for ACSL/C language.")
 ;(description "A longer description")
 ;(depends ocaml dune)
 ;(tags
 ; (topics "to describe" your project)))
 ;)
)
; See the complete stanza docs at https://dune.readthedocs.io/en/stable/dune-files.html#dune-project
